#%RAML 1.0 DataType
type: array
items: 
  properties:
    conjunction:
      type: string
      required: true
    upperCaseCompare:
      type: string
      required: true   
    item: 
      type: array
      items: !include item.raml